### ISSUE TITLE
Separate the scripts within `/scripts/hightlightText.js`

### ISSUE THREAD

**Issue by xnoe** [catogre/catogre-edit#4]
Whilst removing the JS code found within the HTML file and placing them within `/scripts/highlightText.js` I saw that it did more than *just* highlight text.

I didn't feel apt enough with the codebase (or Javascript really) to try and separate them without breaking something in the meanwhile.

To stay in order with the rest of the scripts found in `/scripts/` it may be advisable to separate the file `/scripts/highlightText.js` further, in to clearly labelled files.

It's *also* possible some code may fit better remaining within the `index.html` file.

**Comment by xnoe** [comment]
... and I've only just noticed you already did some of this haha.

**Comment by azureitte** [comment]
hah. yeah I did that
